name: yurufuwa_diary
description: "A gentle diary app for mental care with emotion tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # これがなかったら追加してね
    sdk: flutter  
  
  cached_network_image: ^3.3.1 # 
  # UI関連
  cupertino_icons: ^1.0.6
  fl_chart: ^0.65.0
  
  # Firebase関連
  firebase_core: ^2.30.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  google_sign_in: ^6.1.6
  
  # 状態管理
  provider: ^6.1.1
  
  # ユーティリティ
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  intl: 0.20.2
  path_provider: ^2.1.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # アセット設定
  assets:
    - assets/images/
    
  # フォント設定
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700

