// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADwH-iaa4T2zgPElL5aQTjJ3nKyiA63WI',
    appId: '1:526040431280:web:c9a99680c9f9a91da79975',
    messagingSenderId: '526040431280',
    projectId: 'my-mood-5652c',
    authDomain: 'my-mood-5652c.firebaseapp.com',
    storageBucket: 'my-mood-5652c.firebasestorage.app',
    measurementId: 'G-SR5E0ZDJMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-9V48g2uXiS03vj3GB2xL_qlGY0aMZA',
    appId: '1:526040431280:android:543955fead8a6b74a79975',
    messagingSenderId: '526040431280',
    projectId: 'my-mood-5652c',
    storageBucket: 'my-mood-5652c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjDvECML0lxHlMmsO9i2C-TK8R1PasMQ8',
    appId: '1:526040431280:ios:3c7db0a57b7110fca79975',
    messagingSenderId: '526040431280',
    projectId: 'my-mood-5652c',
    storageBucket: 'my-mood-5652c.firebasestorage.app',
    iosClientId: '526040431280-sg6bhv19i8o1oll1g25730kgfhaerkfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjDvECML0lxHlMmsO9i2C-TK8R1PasMQ8',
    appId: '1:526040431280:ios:3c7db0a57b7110fca79975',
    messagingSenderId: '526040431280',
    projectId: 'my-mood-5652c',
    storageBucket: 'my-mood-5652c.firebasestorage.app',
    iosClientId: '526040431280-sg6bhv19i8o1oll1g25730kgfhaerkfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADwH-iaa4T2zgPElL5aQTjJ3nKyiA63WI',
    appId: '1:526040431280:web:64a5bd8562452849a79975',
    messagingSenderId: '526040431280',
    projectId: 'my-mood-5652c',
    authDomain: 'my-mood-5652c.firebaseapp.com',
    storageBucket: 'my-mood-5652c.firebasestorage.app',
    measurementId: 'G-9875D673CJ',
  );
}
